### ISSUE TITLE
Just a few spelling mistakes for enter-data.html

### ISSUE THREAD

**Issue by owenvoke** [catheraaine/risk-legacy#13]
Not a problem, but I just noticed that Africa is spelled wrong a few times in [`enter-data.html`](https://github.com/catheraaine/risk-legacy/blob/master/enter-data.html).

`<option>Central Aftica</option>`

This is in a couple of places. 😄 I noticed you'd already changed this in one line for 177d0c1343479ce80e52b44638fbfd6bf9dc3392, but it is repeated in a few other places.

On lines:  
- [ ] 31
- [ ] 114
- [ ] 179
- [ ] 244
- [ ] 309
- [ ] 374

Also, starting on line `519` there may be a possible duplication in the dropdown:

``` html
<li>
    <label for="city">City:</label>
    <select name="city">
        <option>Major City</option>
        <option>Fortified Major City</option>
        <option>Minor City</option>
        <option>Fortified Major City</option>
    </select>
</li>
```

_Fortified Major City_ is used twice, and I was wondering if the last one is meant to be `Fortified Minor City`.

**Comment by catheraaine** [comment]
Thanks!!
