### ISSUE TITLE
node-sass is now needed to build, but isn't a package dependency

### ISSUE THREAD

**Issue by beforan** [catheraaine/risk-legacy#26]
Since the refactor to SASS, getting a local clone up and running requires building the CSS from the SASS source files.

`package.json` contains a "build" task for npm (which incidentally doesn't work on Windows as is), but this uses node-sass, which is not currently a project dependency.
- node-sass should be added as a dev-dependency, so a simple `npm install` will fetch it ready for use.
- `npm build` should be updated to formally run node, so it works on Windows (currently it will only work in bash et al. because Windows cmd/powershell won't interpret the `#!` directive).
- Some docs should be provided (I guess in `Contributing.md`?, so this crosses over with #2 ) to advise devs to get up and running with npm and its tasks.

I'm happy to deal with these and make a pull request.

**Comment by beforan** [comment]
actually maybe the docs would be fine in the README quick start section, rather than `Contributing.md`? Since the quick start steps no longer work as they are.

Not sure which is better.

**Comment by sschadwick** [comment]
Hmm must have gotten lost in the PR merges

**Comment by beforan** [comment]
I guess we can close this since the merge? 👍
