### ISSUE TITLE
Add Sass via npm

### ISSUE THREAD

**Issue by catheraaine** [catheraaine/risk-legacy#5]
Add a Sass build process to the project.

**Comment by allejo** [comment]
This involve porting your current CSS to SCSS? If so, Sass syntax or SCSS syntax?

**Comment by catheraaine** [comment]
The current CSS should aslo work as Sass, and I can use Sass moving forward. Currently I use Sass ruby gem for build. But no refactor of current CSS necessary (I love doing this thing), and it would be Sass not SCSS.

**Comment by allejo** [comment]
Just to clarify, CSS is valid SCSS; [Sass vs SCSS](http://stackoverflow.com/questions/5654447/whats-the-difference-between-scss-and-sass). Is Sass still what you want?
