### ISSUE TITLE
Add npm 

### ISSUE THREAD

**Issue by catheraaine** [catheraaine/risk-legacy#7]

**Comment by duck2** [comment]
How sad, I was very happy to find a web app project without `npm`.

Adding `npm` has the inevitable consequence of `gulp` or `grunt` as the build tool, which will probably run
- `eslint` to keep the coding style consistent
- `mocha` for unit tests, which hugs `bluebird` snugly
- `scss` for ... css stuff
- `JSDoc` for documentation

Those are all nice packages, but I suspect a time will come and people will want to add CSS or JS frameworks for various things and `npm` makes this very easy. In my opinion the bloat they create is less than the opportunity cost of additional hacking on the code. 

I like how is this just some CSS and JS thrown together with `document.write`ing SVG and stuff- so what I would propose is to just `npm install -g` the above packages, orchestrate the build process with `make` and make the distribution via `git clone`.

However note that I am in no position to enforce anything, you can take this as the brushing before the curling stone.
